import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import AuthGuard from '../components/AuthGuard';
import { auth, db } from '../lib/supabase';
const initial={name:'',category:'Vestidos',size:'M',price:'',stock:1,image_url:'',description:'',active:true};
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function Admin(){const[tab,setTab]=useState('Resumo'),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[customers,setCustomers]=useState([]),[form,setForm]=useState(initial),[modal,setModal]=useState(false),[notice,setNotice]=useState('');
 const load=()=>Promise.all([db.products(false),db.orders(),db.profiles()]).then(([p,o,c])=>{setProducts(p);setOrders(o);setCustomers(c)}).catch(e=>setNotice(e.message));useEffect(()=>{load()},[]);
 const revenue=useMemo(()=>orders.reduce((s,o)=>s+Number(o.total),0),[orders]); const save=async e=>{e.preventDefault();try{await db.createProduct({...form,price:Number(form.price),stock:Number(form.stock)});setModal(false);setForm(initial);setNotice('Produto cadastrado com sucesso.');load()}catch(err){setNotice(err.message)}};
 return <AuthGuard admin><Head><title>Admin | ReVeste</title></Head><div className="admin-shell"><aside className="admin-side"><div className="brand"><span className="brand-mark">R</span><span>Re<span>Veste</span></span></div><p>GESTÃO DA LOJA</p>{['Resumo','Produtos','Pedidos','Clientes'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x==='Resumo'?'⌂':x==='Produtos'?'◇':x==='Pedidos'?'▣':'♙'} {x}</button>)}<Link href="/loja">↗ Ver loja online</Link><button className="admin-logout" onClick={()=>{auth.signOut();location.href='/login'}}>Sair</button></aside><main className="admin-main"><header><div><p className="eyebrow">PAINEL ADMINISTRATIVO</p><h1>{tab}</h1></div><button className="shop-primary" onClick={()=>setModal(true)}>+ Novo produto</button></header>{notice&&<div className="admin-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {tab==='Resumo'&&<><section className="admin-stats"><article><span>Faturamento</span><strong>{money(revenue)}</strong><small>Total de pedidos</small></article><article><span>Pedidos</span><strong>{orders.length}</strong><small>{orders.filter(o=>o.status==='pendente').length} aguardando</small></article><article><span>Produtos ativos</span><strong>{products.filter(p=>p.active).length}</strong><small>{products.filter(p=>p.stock<2).length} com estoque baixo</small></article><article><span>Clientes</span><strong>{customers.filter(c=>c.role==='customer').length}</strong><small>Contas cadastradas</small></article></section><AdminTable title="Pedidos recentes" heads={['Pedido','Cliente','Status','Total']} rows={orders.slice(0,6).map(o=>[o.id.slice(0,8),o.customer_name||'Cliente',o.status,money(o.total)])}/></>}
 {tab==='Produtos'&&<AdminTable title="Catálogo" heads={['Produto','Categoria','Tamanho','Estoque','Preço','']} rows={products.map(p=>[p.name,p.category,p.size,p.stock,money(p.price),<button key={p.id} onClick={async()=>{if(confirm('Excluir esta peça?')){await db.deleteProduct(p.id);load()}}}>Excluir</button>])}/>} 
 {tab==='Pedidos'&&<AdminTable title="Todos os pedidos" heads={['Pedido','Data','Cliente','Pagamento','Status','Total']} rows={orders.map(o=>[o.id.slice(0,8),new Date(o.created_at).toLocaleDateString('pt-BR'),o.customer_name||'Cliente',o.payment_method,o.status,money(o.total)])}/>} 
 {tab==='Clientes'&&<AdminTable title="Clientes cadastrados" heads={['Nome','E-mail','Perfil','Cadastro']} rows={customers.map(c=>[c.name,c.email,c.role,new Date(c.created_at).toLocaleDateString('pt-BR')])}/>} </main>
 {modal&&<div className="modal-overlay"><form className="product-modal" onSubmit={save}><div><h2>Cadastrar nova peça</h2><button type="button" onClick={()=>setModal(false)}>×</button></div><label>Nome da peça<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-row"><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Vestidos','Casacos','Acessórios','Camisas','Calças','Calçados'].map(x=><option key={x}>{x}</option>)}</select></label><label>Tamanho<input required value={form.size} onChange={e=>setForm({...form,size:e.target.value})}/></label></div><div className="form-row"><label>Preço<input required min="0" step="0.01" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Estoque<input required min="0" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label></div><label>URL da imagem<input type="url" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://..."/></label><label>Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="shop-primary">Salvar produto</button></form></div>}</div></AuthGuard>}
function AdminTable({title,heads,rows}){return <section className="admin-table"><h2>{title}</h2><div className="table-scroll"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Nenhum registro encontrado.</td></tr>}</tbody></table></div></section>}
