import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import AuthGuard from '../components/AuthGuard';
import Link from '../src/shims/Link';
import Head from '../src/shims/Head';
import { db, getSession } from '../lib/supabase';

export default function EmployeeDetail(){
  const{id}=useParams();
  const[employee,setEmployee]=useState(null),[form,setForm]=useState(null),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{db.employee(id).then(data=>{setEmployee(data);const detail=data?.employee_details?.[0]||{};setForm({id,role:data?.role||'cashier',job_title:detail.job_title||'',department:detail.department||'',admission_date:detail.admission_date||'',salary:detail.salary??'',employment_status:detail.employment_status||'active',notes:detail.notes||''})}).catch(error=>setNotice(error.message))},[id]);
  const submit=async event=>{event.preventDefault();setSaving(true);setNotice('');try{const response=await fetch('/api/admin/staff',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${getSession()?.access_token}`},body:JSON.stringify(form)}),data=await response.json();if(!response.ok)throw new Error(data.message);setNotice(data.access_blocked?'Dados salvos e acesso bloqueado.':'Dados funcionais e acesso atualizados.')}catch(error){setNotice(error.message)}finally{setSaving(false)}};
  return <AuthGuard roles={['admin']}><Head><title>Funcionário | ReVeste</title></Head><main className="employee-detail-page"><header><div><Link href="/equipe">← Voltar à equipe</Link><p className="eyebrow">CADASTRO FUNCIONAL</p><h1>{employee?.name||'Funcionário'}</h1><span>{employee?.email}</span></div></header>{notice&&<div className="admin-notice">{notice}</div>}{form?<form className="employee-editor" onSubmit={submit}><section><h2>Acesso ao sistema</h2><label>Nível de acesso<select value={form.role} onChange={event=>setForm({...form,role:event.target.value})}><option value="cashier">Operador de caixa</option><option value="inventory">Estoque</option><option value="manager">Gerente</option><option value="admin">Administrador</option></select></label><label>Situação funcional<select value={form.employment_status} onChange={event=>setForm({...form,employment_status:event.target.value})}><option value="active">Ativo — acesso permitido</option><option value="leave">Afastado — acesso bloqueado</option><option value="terminated">Desligado — acesso bloqueado</option></select></label><p className="settings-hint">Funcionários afastados ou desligados são bloqueados também no Supabase Auth.</p></section><section><h2>Dados profissionais</h2><div className="form-row"><label>Cargo<input value={form.job_title} onChange={event=>setForm({...form,job_title:event.target.value})}/></label><label>Departamento<input value={form.department} onChange={event=>setForm({...form,department:event.target.value})}/></label></div><div className="form-row"><label>Data de admissão<input type="date" value={form.admission_date} onChange={event=>setForm({...form,admission_date:event.target.value})}/></label><label>Salário<input type="number" min="0" step="0.01" value={form.salary} onChange={event=>setForm({...form,salary:event.target.value})}/></label></div><label>Observações internas<textarea maxLength="2000" value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></label><button className="shop-primary" disabled={saving}>{saving?'Salvando...':'Salvar alterações'}</button></section></form>:<div className="page-loader"><p>Carregando cadastro...</p></div>}</main></AuthGuard>;
}
