import Head from '../src/shims/Head';
import Link from '../src/shims/Link';
import { useEffect, useMemo, useState } from 'react';
import { auth, configured, db, getSession } from '../lib/supabase';

const demo = [
  {id:'d1',name:'Vestido Floral Vintage',category:'Vestidos',size:'M',price:89.9,stock:1,image_url:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=700'},
  {id:'d2',name:'Jaqueta Jeans Oversized',category:'Casacos',size:'G',price:129.9,stock:2,image_url:'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=700'},
  {id:'d3',name:'Bolsa Couro Caramelo',category:'Acessórios',size:'Único',price:74.9,stock:1,image_url:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=700'},
  {id:'d4',name:'Camisa Linho Natural',category:'Camisas',size:'P',price:65.9,stock:3,image_url:'https://images.unsplash.com/photo-1605763240000-7e93b172d754?w=700'},
  {id:'d5',name:'Calça Alfaiataria Bege',category:'Calças',size:'38',price:98.9,stock:1,image_url:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=700'},
  {id:'d6',name:'Tênis Retrô Branco',category:'Calçados',size:'37',price:119.9,stock:1,image_url:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=700'}
];
const money = n => Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function Store() {
  const [products,setProducts]=useState(demo),[cart,setCart]=useState(()=>{try{return JSON.parse(localStorage.getItem('reveste_cart')||'[]')}catch{return[]}}),[query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[size,setSize]=useState('Todos'),[sort,setSort]=useState('recentes'),[maxPrice,setMaxPrice]=useState(500),[open,setOpen]=useState(false),[filters,setFilters]=useState(false),[loading,setLoading]=useState(configured),[message,setMessage]=useState(''),[session,setSession]=useState(null),[settings,setSettings]=useState({store_name:'ReVeste',tagline:'Moda circular para histórias que continuam.',primary_color:'#315d4a',accent_color:'#b36f53',hero_title:'Estilo que renasce com você.',hero_subtitle:'Peças únicas, escolhidas com carinho para durar muitas histórias — inclusive a sua.',pix_enabled:false,card_enabled:false,mercadopago_enabled:false,stripe_enabled:false,pagbank_enabled:false});
  useEffect(()=>{setSession(getSession());if(configured) Promise.all([db.products(),db.settings()]).then(([items,config])=>{setProducts(items);if(config)setSettings(config)}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{localStorage.setItem('reveste_cart',JSON.stringify(cart))},[cart]);
  const filtered=useMemo(()=>products.filter(p=>(category==='Todos'||p.category===category)&&(size==='Todos'||p.size===size)&&Number(p.price)<=maxPrice&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='menor'?a.price-b.price:sort==='maior'?b.price-a.price:sort==='nome'?a.name.localeCompare(b.name):new Date(b.created_at||0)-new Date(a.created_at||0)),[products,category,size,maxPrice,query,sort]);
  const total=cart.reduce((sum,p)=>sum+Number(p.price),0);
  const addToCart=product=>{if(cart.filter(item=>item.id===product.id).length>=Number(product.stock||1))return setMessage('Você já adicionou todo o estoque disponível desta peça.');setCart([...cart,product]);setMessage(`${product.name} foi adicionada à sacola.`)};
  if(settings.maintenance_mode)return <><Head><title>{settings.store_name} | Manutenção</title><meta name="robots" content="noindex,nofollow"/></Head><main className="maintenance-page"><div className="brand-mark">{settings.store_name?.charAt(0)}</div><p>ESTAMOS PREPARANDO NOVIDADES</p><h1>Loja temporariamente em manutenção.</h1><span>Estamos organizando o closet para oferecer uma experiência ainda melhor. Volte em breve.</span>{settings.instagram&&<a href={settings.instagram}>Acompanhe as novidades no Instagram</a>}</main></>;
  const brand=<div className="brand">{settings.logo_url?<img className="custom-logo" src={settings.logo_url} alt={settings.store_name}/>:<span className="brand-mark">{settings.store_name.charAt(0)}</span>}<span>{settings.store_name}</span></div>;
  return <><Head><title>{settings.seo_title||`${settings.store_name} | Brechó online`}</title><meta name="description" content={settings.seo_description||settings.tagline}/></Head><div className="store-page" style={{'--green':settings.primary_color,'--brand-accent':settings.accent_color}}>
    <div className="store-announcement"><span>♻ Moda circular com propósito</span><b>Frete grátis acima de {money(settings.free_shipping_threshold||250)}</b><span>Compra protegida</span></div><header className="store-header"><Link href="/loja">{brand}</Link><nav><a href="#novidades">Novidades</a><a href="#catalogo">Comprar</a><a href="#sobre">Nossa história</a><Link href="/doar">Doe suas peças</Link></nav><div className="store-tools"><button onClick={()=>document.querySelector('.store-search input').focus()}>⌕</button><Link href={session?'/notificacoes':'/login?next=/notificacoes'} aria-label="Notificações">♢</Link><Link href={session?'/favoritos':'/login?next=/favoritos'} aria-label="Favoritos">♡</Link><Link href={session?'/minha-conta':'/login'}>♙</Link><button onClick={()=>setOpen(true)}>Sacola <b>{cart.length}</b></button></div></header>
    <section className="hero" id="novidades" style={settings.hero_image?{backgroundImage:`linear-gradient(90deg,rgba(31,50,42,.86),rgba(31,50,42,.15)),url(${settings.hero_image})`}:undefined}><div><span>CURADORIA ESPECIAL</span><h1>{settings.hero_title}</h1><p>{settings.hero_subtitle}</p><a href="#catalogo" className="shop-primary">Descobrir peças →</a><small>♻ Moda circular &nbsp; · &nbsp; ✓ Curadoria cuidadosa</small></div></section>
    <section className="store-benefits"><span>✦ Peças únicas</span><span>♻ Consumo consciente</span><span>⌁ Envio para todo Brasil</span><span>♡ Compra segura</span></section>
    <section className="catalog" id="catalogo"><div className="catalog-head"><div><span className="section-kicker">ESCOLHIDAS PARA VOCÊ</span><h2>Novidades no closet</h2></div><div className="store-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar uma peça..."/><span>⌕</span></div></div>
      <div className="catalog-tools"><div className="category-pills">{['Todos',...new Set(products.map(p=>p.category))].map(c=><button className={c===category?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><button className="filter-toggle" onClick={()=>setFilters(!filters)}>⚙ Filtros {size!=='Todos'?'· 1':''}</button></div>{filters&&<div className="advanced-filters"><label>Tamanho<select value={size} onChange={e=>setSize(e.target.value)}><option>Todos</option>{[...new Set(products.map(p=>p.size))].map(x=><option key={x}>{x}</option>)}</select></label><label>Preço até <b>{money(maxPrice)}</b><input type="range" min="20" max="500" step="10" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label><label>Ordenar<select value={sort} onChange={e=>setSort(e.target.value)}><option value="recentes">Mais recentes</option><option value="menor">Menor preço</option><option value="maior">Maior preço</option><option value="nome">Nome A–Z</option></select></label><button onClick={()=>{setSize('Todos');setMaxPrice(500);setSort('recentes')}}>Limpar filtros</button></div>}
      {message&&<div className="store-message">{message}</div>}{loading?<div className="store-skeleton">{[1,2,3,4].map(x=><i key={x}/>)}</div>:filtered.length?<div className="shop-grid">{filtered.map(p=><article className="shop-card" key={p.id}><div className="shop-image"><Link href={`/produto/${p.id}`}><img src={p.image_url||'/placeholder.svg'} alt={p.name}/></Link><span>PEÇA ÚNICA</span><button aria-label={`Adicionar ${p.name} à sacola`} onClick={()=>addToCart(p)}>+</button></div><p>{p.category}</p><h3><Link href={`/produto/${p.id}`}>{p.name}</Link></h3><div><span>Tam. {p.size}</span><strong>{money(p.price)}</strong></div></article>)}</div>:<div className="catalog-empty"><span>◇</span><h3>Nenhuma peça encontrada</h3><p>Tente remover algum filtro ou buscar por outro termo.</p><button onClick={()=>{setQuery('');setCategory('Todos');setSize('Todos');setMaxPrice(500)}}>Limpar filtros</button></div>}
    </section>
    <section className="story" id="sobre"><div><span className="section-kicker">NOSSO PROPÓSITO</span><h2>Roupa boa não<br/>nasce para ser descartada.</h2><p>Acreditamos em uma moda mais gentil com o planeta. Cada peça é higienizada, avaliada e preparada para viver uma nova história.</p><Link href="/login">Faça parte desse movimento →</Link></div></section>
    <footer className="store-footer"><div className="footer-brand">{brand}<p>{settings.tagline||`Moda circular com propósito.`}</p></div><div className="footer-socials">{[[settings.instagram,'Instagram'],[settings.facebook,'Facebook'],[settings.x_url,'X'],[settings.tiktok,'TikTok'],[settings.whatsapp,'WhatsApp'],[settings.marketplace_mercadolivre,'Mercado Livre'],[settings.marketplace_shopee,'Shopee']].filter(([url])=>url).map(([url,label])=><a href={label==='WhatsApp'&&!String(url).startsWith('http')?`https://wa.me/${String(url).replace(/\D/g,'')}`:url} target="_blank" rel="noreferrer" key={label}>{label}</a>)}</div><small>© 2026 <b>{settings.store_name}</b>. Feito com propósito.</small><Link href="/admin">Área administrativa</Link></footer>
    {open&&<div className="cart-overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><div className="cart-title"><h2>Sua sacola <small>{cart.length} itens</small></h2><button onClick={()=>setOpen(false)}>×</button></div>{cart.length===0?<div className="empty-cart">Sua sacola está vazia.<button onClick={()=>setOpen(false)}>Continuar comprando</button></div>:<><div className="cart-items">{cart.map((p,i)=><div key={`${p.id}-${i}`}><img src={p.image_url} alt=""/><span><strong>{p.name}</strong><small>Tam. {p.size}</small><b>{money(p.price)}</b></span><button onClick={()=>setCart(cart.filter((_,x)=>x!==i))}>×</button></div>)}</div><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><div className="payment-options"><p>Pagamento seguro</p><small>{(settings.pix_enabled&&(settings.mercadopago_enabled||settings.pagbank_enabled))?'Pix disponível. ':''}{(settings.card_enabled&&(settings.stripe_enabled||settings.mercadopago_enabled))?'Cartão disponível. ':''}Você escolhe a forma na próxima etapa.</small></div><button className="shop-primary" onClick={()=>{localStorage.setItem('reveste_checkout',JSON.stringify(cart));sessionStorage.setItem('reveste_checkout_key',crypto.randomUUID());location.href='/checkout'}}>Continuar para entrega</button><small>🔒 Pagamento processado em ambiente protegido</small></>}</aside></div>}
  </div></>;
}
