import { useEffect, useMemo, useState } from 'react';
import AuthGuard from '../components/AuthGuard';
import Link from '../src/shims/Link';
import { db } from '../lib/supabase';

const statusLabel = value => value==='leave'?'Afastado':value==='terminated'?'Desligado':'Ativo';
const csvCell = value => `"${String(value??'').replaceAll('"','""')}"`;

export default function HR(){
  const [employees,setEmployees]=useState([]),[entries,setEntries]=useState([]),[query,setQuery]=useState(''),[department,setDepartment]=useState('todos'),[status,setStatus]=useState('todos'),[notice,setNotice]=useState('');
  useEffect(()=>{Promise.all([db.employees(),db.timeEntries()]).then(([people,times])=>{setEmployees(people);setEntries(times)}).catch(error=>setNotice(error.message))},[]);
  const hours=useMemo(()=>entries.filter(entry=>entry.clock_out).reduce((sum,entry)=>sum+(new Date(entry.clock_out)-new Date(entry.clock_in))/36e5,0),[entries]);
  const departments=useMemo(()=>[...new Set(employees.map(employee=>employee.employee_details?.[0]?.department).filter(Boolean))].sort(),[employees]);
  const filtered=useMemo(()=>employees.filter(employee=>{const detail=employee.employee_details?.[0]||{},employment=detail.employment_status||'active',text=`${employee.name} ${employee.email} ${detail.job_title||''} ${detail.department||''}`.toLowerCase();return text.includes(query.toLowerCase())&&(department==='todos'||detail.department===department)&&(status==='todos'||employment===status)}),[employees,query,department,status]);
  const exportCsv=()=>{const rows=[['Nome','E-mail','Cargo','Departamento','Admissão','Situação'],...filtered.map(employee=>{const detail=employee.employee_details?.[0]||{};return[employee.name,employee.email,detail.job_title||employee.role,detail.department||'Loja',detail.admission_date||'',statusLabel(detail.employment_status)]})];const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}));link.download=`quadro-funcional-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)};
  return <AuthGuard roles={['admin','manager']}><main className="ops-page"><header className="ops-head"><div><p className="eyebrow">RECURSOS HUMANOS</p><h1>RH e jornada</h1><span>Visão de quadro, departamentos, admissões e horas registradas.</span></div><button onClick={exportCsv}>↓ Exportar quadro</button></header>{notice&&<div className="admin-notice">{notice}</div>}<section className="ops-kpis"><article><small>Funcionários ativos</small><strong>{employees.filter(employee=>(employee.employee_details?.[0]?.employment_status||'active')==='active').length}</strong></article><article><small>Departamentos</small><strong>{departments.length}</strong></article><article><small>Horas registradas</small><strong>{hours.toFixed(1)}h</strong></article><article><small>Em jornada agora</small><strong>{entries.filter(entry=>!entry.clock_out).length}</strong></article></section><section className="ops-card ops-table"><div className="people-filters"><label>Pesquisar<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Nome, e-mail, cargo..."/></label><label>Departamento<select value={department} onChange={event=>setDepartment(event.target.value)}><option value="todos">Todos</option>{departments.map(value=><option key={value}>{value}</option>)}</select></label><label>Situação<select value={status} onChange={event=>setStatus(event.target.value)}><option value="todos">Todas</option><option value="active">Ativos</option><option value="leave">Afastados</option><option value="terminated">Desligados</option></select></label><span>{filtered.length} resultado(s)</span></div><div className="table-scroll"><table><thead><tr><th>Funcionário</th><th>Cargo</th><th>Departamento</th><th>Admissão</th><th>Situação</th><th/></tr></thead><tbody>{filtered.length?filtered.map(employee=>{const detail=employee.employee_details?.[0]||{};return <tr key={employee.id}><td><b>{employee.name}</b><small>{employee.email}</small></td><td>{detail.job_title||employee.role}</td><td>{detail.department||'Loja'}</td><td>{detail.admission_date?new Date(`${detail.admission_date}T12:00`).toLocaleDateString('pt-BR'):'—'}</td><td><span className={`employment-status ${detail.employment_status||'active'}`}>{statusLabel(detail.employment_status)}</span></td><td><Link href={`/equipe/${employee.id}`}>Abrir cadastro →</Link></td></tr>}):<tr><td colSpan="6">Nenhum funcionário encontrado com estes filtros.</td></tr>}</tbody></table></div></section></main></AuthGuard>;
}
