-- Caixa completo, eventos de rastreio e meios de pagamento configuráveis.
alter table public.store_settings add column if not exists stripe_enabled boolean default false;
alter table public.store_settings add column if not exists mercadopago_enabled boolean default true;
alter table public.store_settings add column if not exists pagbank_enabled boolean default false;
alter table public.store_settings add column if not exists pix_enabled boolean default true;
alter table public.store_settings add column if not exists card_enabled boolean default true;
alter table public.store_settings add column if not exists cash_enabled boolean default true;
create table if not exists public.cash_sessions(id uuid primary key default gen_random_uuid(),operator_id uuid not null references profiles(id),opening_balance numeric(10,2) not null default 0,status text not null default 'open',opened_at timestamptz not null default now(),closed_at timestamptz,expected_balance numeric(10,2),counted_balance numeric(10,2),difference numeric(10,2),closing_notes text);
create table if not exists public.cash_movements(id uuid primary key default gen_random_uuid(),session_id uuid not null references cash_sessions(id) on delete cascade,operator_id uuid not null references profiles(id),type text not null check(type in('sale','supply','withdrawal')),amount numeric(10,2) not null check(amount>=0),reason text,order_id uuid references orders(id),created_at timestamptz not null default now());
create table if not exists public.tracking_events(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id) on delete cascade,status text not null,description text not null,location text,occurred_at timestamptz not null default now(),created_by uuid default auth.uid() references profiles(id));
alter table public.cash_sessions enable row level security;alter table public.cash_movements enable row level security;alter table public.tracking_events enable row level security;
create policy "equipe ve caixas" on public.cash_sessions for select using(operator_id=auth.uid() or has_system_role(array['admin','manager']));
create policy "equipe ve movimentos" on public.cash_movements for select using(operator_id=auth.uid() or has_system_role(array['admin','manager']));
create policy "cliente ve rastreio" on public.tracking_events for select using(exists(select 1 from orders where orders.id=order_id and(customer_id=auth.uid() or has_system_role(array['admin','manager']))));
create policy "equipe registra rastreio" on public.tracking_events for insert with check(has_system_role(array['admin','manager']));
create or replace function public.open_cash_session(p_opening_balance numeric) returns uuid language plpgsql security definer set search_path=public as $$ declare new_id uuid;begin if not has_system_role(array['admin','manager','cashier']) then raise exception 'Acesso negado';end if;if exists(select 1 from cash_sessions where operator_id=auth.uid() and status='open')then raise exception 'Você já possui um caixa aberto';end if;insert into cash_sessions(operator_id,opening_balance)values(auth.uid(),greatest(p_opening_balance,0))returning id into new_id;return new_id;end;$$;
create or replace function public.add_cash_movement(p_movement_type text,p_amount numeric,p_reason text) returns uuid language plpgsql security definer set search_path=public as $$ declare sid uuid;mid uuid;begin select id into sid from cash_sessions where operator_id=auth.uid() and status='open' order by opened_at desc limit 1;if sid is null then raise exception 'Abra o caixa primeiro';end if;if p_movement_type not in('supply','withdrawal')then raise exception 'Movimento inválido';end if;insert into cash_movements(session_id,operator_id,type,amount,reason)values(sid,auth.uid(),p_movement_type,greatest(p_amount,0),p_reason)returning id into mid;return mid;end;$$;
create or replace function public.close_cash_session(p_counted_balance numeric,p_closing_notes text) returns uuid language plpgsql security definer set search_path=public as $$ declare s cash_sessions%rowtype;expected numeric;begin select * into s from cash_sessions where operator_id=auth.uid() and status='open' order by opened_at desc limit 1 for update;if s.id is null then raise exception 'Nenhum caixa aberto';end if;select s.opening_balance+coalesce(sum(case when type in('sale','supply')then amount else -amount end),0)into expected from cash_movements where session_id=s.id;update cash_sessions set status='closed',closed_at=now(),expected_balance=expected,counted_balance=p_counted_balance,difference=p_counted_balance-expected,closing_notes=p_closing_notes where id=s.id;return s.id;end;$$;
create or replace function public.create_pos_order(payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare new_id uuid;sid uuid;item jsonb;product_record products%rowtype;subtotal numeric:=0;discount numeric:=0;method text;
begin if not has_system_role(array['admin','manager','cashier'])then raise exception 'Acesso ao caixa não autorizado';end if;select id into sid from cash_sessions where operator_id=auth.uid()and status='open' order by opened_at desc limit 1;if sid is null then raise exception 'Abra o caixa antes de realizar vendas';end if;if jsonb_array_length(payload->'items')=0 then raise exception 'Adicione um produto';end if;for item in select*from jsonb_array_elements(payload->'items')loop select*into product_record from products where id=(item->>'product_id')::uuid and active=true for update;if product_record.id is null or product_record.stock<(item->>'quantity')::int then raise exception 'Produto sem estoque';end if;subtotal:=subtotal+product_record.price*(item->>'quantity')::int;end loop;discount:=greatest(0,least(coalesce((payload->>'discount')::numeric,0),subtotal));method:=coalesce(payload->>'payment_method','dinheiro');insert into orders(customer_id,customer_name,total,status,payment_method,payment_provider)values(auth.uid(),coalesce(nullif(payload->>'customer_name',''),'Consumidor final'),subtotal-discount,'pago',method,'pdv')returning id into new_id;for item in select*from jsonb_array_elements(payload->'items')loop select*into product_record from products where id=(item->>'product_id')::uuid for update;insert into order_items(order_id,product_id,quantity,unit_price)values(new_id,product_record.id,(item->>'quantity')::int,product_record.price);update products set stock=stock-(item->>'quantity')::int,updated_at=now()where id=product_record.id;end loop;if method='dinheiro'then insert into cash_movements(session_id,operator_id,type,amount,reason,order_id)values(sid,auth.uid(),'sale',subtotal-discount,'Venda presencial',new_id);end if;return new_id;end;$$;
