-- Dados completos do cliente, endereços e checkout com frete.
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists document text;
create table if not exists public.customer_addresses(id uuid primary key default gen_random_uuid(),customer_id uuid not null default auth.uid() references profiles(id) on delete cascade,label text default 'Principal',zip_code text not null,street text not null,number text not null,complement text,neighborhood text not null,city text not null,state text not null,is_default boolean default false,created_at timestamptz not null default now());
alter table public.customer_addresses enable row level security;
create policy "cliente ve enderecos" on public.customer_addresses for select using(customer_id=auth.uid());
create policy "cliente cria enderecos" on public.customer_addresses for insert with check(customer_id=auth.uid() and exists(select 1 from profiles where id=auth.uid() and role='customer'));
create policy "cliente exclui enderecos" on public.customer_addresses for delete using(customer_id=auth.uid());
create or replace function public.update_my_details(p_name text,p_phone text,p_document text) returns void language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from profiles where id=auth.uid() and role='customer')then raise exception 'Conta não pertence a um cliente';end if;update profiles set name=p_name,phone=p_phone,document=p_document where id=auth.uid();end;$$;
create or replace function public.create_order(payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare new_id uuid;item jsonb;product_record products%rowtype;order_total numeric:=0;freight numeric:=0;profile_name text;
begin if auth.uid()is null or not exists(select 1 from profiles where id=auth.uid()and role='customer')then raise exception 'Entre com uma conta de cliente';end if;if jsonb_array_length(payload->'items')=0 then raise exception 'A sacola está vazia';end if;select name into profile_name from profiles where id=auth.uid();for item in select*from jsonb_array_elements(payload->'items')loop select*into product_record from products where id=(item->>'product_id')::uuid and active=true for update;if product_record.id is null or product_record.stock<(item->>'quantity')::int then raise exception 'Uma peça ficou indisponível';end if;order_total:=order_total+product_record.price*(item->>'quantity')::int;end loop;freight:=greatest(coalesce((payload->>'shipping_cost')::numeric,0),0);insert into orders(customer_id,customer_name,total,payment_method,shipping_address,shipping_service,shipping_cost)values(auth.uid(),profile_name,order_total+freight,coalesce(payload->>'payment_method','pix'),payload->'shipping_address',payload->>'shipping_method',freight)returning id into new_id;for item in select*from jsonb_array_elements(payload->'items')loop select*into product_record from products where id=(item->>'product_id')::uuid for update;insert into order_items(order_id,product_id,quantity,unit_price)values(new_id,product_record.id,(item->>'quantity')::int,product_record.price);update products set stock=stock-(item->>'quantity')::int,updated_at=now()where id=product_record.id;end loop;return new_id;end;$$;
