-- Reservas abandonadas não podem bloquear peças únicas indefinidamente.
alter table public.orders add column if not exists pending_expires_at timestamptz default(now()+interval '24 hours');
update public.orders set pending_expires_at=created_at+interval '24 hours' where status='pendente' and pending_expires_at is null;
create index if not exists orders_pending_expiration_idx on public.orders(pending_expires_at) where status='pendente';

create or replace function public.reconcile_order_payment(p_order_id uuid,p_status text,p_reference text default null)returns order_status language plpgsql security definer set search_path=public as $$declare current_order orders%rowtype;next_status order_status;item record;begin select*into current_order from orders where id=p_order_id for update;if current_order.id is null then raise exception 'Pedido não encontrado';end if;if current_order.status='cancelado'and p_status='pago'then raise exception 'Pedido cancelado exige conciliação manual para evitar divergência de estoque';end if;next_status:=case when p_status='pago'then'pago'::order_status when p_status='cancelado'then'cancelado'::order_status else current_order.status end;if current_order.status in('pago','separando','enviado','concluido')then next_status:=current_order.status;end if;if current_order.status='pendente'and next_status='cancelado'then for item in select product_id,quantity from order_items where order_id=p_order_id and product_id is not null loop update products set stock=stock+item.quantity,updated_at=now()where id=item.product_id;end loop;if current_order.coupon_code is not null then update coupons set used_count=greatest(0,used_count-1)where code=current_order.coupon_code;end if;end if;update orders set status=next_status,payment_reference=coalesce(nullif(p_reference,''),payment_reference),payment_checked_at=now(),paid_at=case when next_status='pago'then coalesce(paid_at,now())else paid_at end,cancelled_at=case when next_status='cancelado'then coalesce(cancelled_at,now())else cancelled_at end where id=p_order_id;return next_status;end;$$;
revoke all on function public.reconcile_order_payment(uuid,text,text)from public,anon,authenticated;grant execute on function public.reconcile_order_payment(uuid,text,text)to service_role;

create or replace function public.expire_pending_orders(p_limit integer default 200)returns integer language plpgsql security definer set search_path=public as $$declare candidate record;expired_count integer:=0;begin for candidate in select id from orders where status='pendente'and pending_expires_at<=now()order by pending_expires_at for update skip locked limit greatest(1,least(coalesce(p_limit,200),1000))loop perform reconcile_order_payment(candidate.id,'cancelado','expired_by_system');expired_count:=expired_count+1;end loop;return expired_count;end;$$;
revoke all on function public.expire_pending_orders(integer)from public,anon,authenticated;grant execute on function public.expire_pending_orders(integer)to service_role;
