import crypto from 'crypto';
export const config = { api: { bodyParser: false } };
const readBody=req=>new Promise((resolve,reject)=>{const chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)});
const mapStatus=status=>['approved','paid','PAID'].includes(status)?'pago':['cancelled','canceled','rejected','DECLINED'].includes(status)?'cancelado':'pendente';
async function updateOrder(orderId,status,reference){const base=(process.env.VITE_SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL),key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!orderId||!key)return;await fetch(`${base}/rest/v1/orders?id=eq.${encodeURIComponent(orderId)}`,{method:'PATCH',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({status:mapStatus(status),payment_reference:String(reference||'')})});}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).end();try{const provider=req.query.provider;const raw=await readBody(req);const payload=JSON.parse(raw.toString()||'{}');
 if(provider==='stripe'){const secret=process.env.STRIPE_WEBHOOK_SECRET,signature=req.headers['stripe-signature'];if(!secret||!signature)throw new Error('Assinatura ausente');const parts=Object.fromEntries(signature.split(',').map(x=>x.split('=')));const expected=crypto.createHmac('sha256',secret).update(`${parts.t}.${raw}`).digest('hex');if(!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(parts.v1||'')))throw new Error('Assinatura inválida');const session=payload.data?.object;await updateOrder(session?.client_reference_id,session?.payment_status,session?.id);}
 else if(provider==='mercadopago'){const id=payload.data?.id||req.query['data.id'];const response=await fetch(`https://api.mercadopago.com/v1/payments/${id}`,{headers:{Authorization:`Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`}});const payment=await response.json();if(!response.ok)throw new Error('Notificação inválida');await updateOrder(payment.external_reference,payment.status,payment.id);}
 else if(provider==='pagbank'){await updateOrder(payload.reference_id,payload.charges?.[0]?.status,payload.id);}
 else throw new Error('Provedor inválido');return res.status(200).json({received:true});}catch(error){return res.status(400).json({message:error.message});}}
